# Intro to PyTorch

---

## Section 0: Importing Libraries

Libraries such as PyTorch, NumPy, NLTK, and many others contain functions and methods that you can use in your code, and are often very useful. Libraries must be installed, which is usually done through Package Installer for Python `pip`. We have already installed all the libraries you need for this course on your device.

However, when writing code, you must **import** those libraries into your code, so they can be used.

In [13]:
import torch # here we are importing PyTorch

While importing, we can rename the library, usually something shorter, so we don't have to retype the longer name every time we call a function from that library.

In [14]:
import numpy as np 
# from now on, we can refer to numpy as np, so we save time while writing code

To use functions, methods, pre-written code in general from a library, we use **dot notation** to access the methods within the library. 

In [16]:
a = np.array([1,2,3])

*Note*: No need to worry about specific `numpy` functions for now. 

---

## Section 1: Tensors

**Tensors** are a special data structure in PyTorch, which are like a `list`, but allow us to do more powerful, machine learning related computations much easier. PyTorch tensors are built on NumPy arrays, which are also like lists.

In [19]:
x = torch.tensor(2.0)
print(x)

tensor([2.])


In [20]:
# Multi-dimensional tensor
y = torch.tensor([[2.0, 3.0], [1.0, 6.0]])
print(y)


tensor([[2., 3.],
        [1., 6.]])


Basic operations can also be done to tensors.

In [25]:
a = torch.rand(2,2) # creates a 2x2 tensor with random values between 0 and 1
b = torch.rand(2,2)
c = a + b
d = a - b
e = a * b
f = a / b

print('a ', a)
print('b ', b)
print('c ', c)
print('d ', d)
print('e ', e)
print('f ', f)

a  tensor([[0.9285, 0.2098],
        [0.4366, 0.4695]])
b  tensor([[0.6961, 0.1384],
        [0.1186, 0.3853]])
c  tensor([[1.6246, 0.3482],
        [0.5552, 0.8548]])
d  tensor([[0.2323, 0.0713],
        [0.3179, 0.0842]])
e  tensor([[0.6463, 0.0290],
        [0.0518, 0.1809]])
f  tensor([[1.3338, 1.5152],
        [3.6797, 1.2184]])


To get the element from a tensor with 1 element, we have to use the `.item()` method.

In [26]:
x = torch.tensor(2.0)
print(x) # prints the whole tensor
print(x.item()) # prints the value inside the tensor

tensor(2.)
2.0


To get the dimensions of a tensor, use the `.size()` method.

In [29]:
y = torch.rand(5,3) # 5x3 tensor with random values from 0 to 1
print(y.size())

torch.Size([5, 3])


To get a specific element from a tensor, use indexing.

In [33]:
y = torch.rand(2,3)
print(y)
print(y[0,2])

tensor([[0.3273, 0.4554, 0.0858],
        [0.4682, 0.2158, 0.6559]])
tensor(0.0858)


---

## Section 2: Gradient Calculation

Tensors in PyTorch allow us to calculate gradients very easily, using the Autograd package. 

To use this, we need to specify `requires_grad = True`, to let PyTorch know it needs to keep track of the gradients as we go through our calculations.

In [41]:
x = torch.rand(5, requires_grad=True)

Now we can manipulate our tensors any way we like.

In [42]:
y = 2 * x
print(y)

tensor([0.7911, 0.2740, 1.4945, 0.2830, 1.2478], grad_fn=<MulBackward0>)


In [43]:
c = y * y * y
print(c)

tensor([0.4951, 0.0206, 3.3383, 0.0227, 1.9430], grad_fn=<MulBackward0>)


We want our final output to be just 1 number. There are many ways to do this.

In [44]:
c = c.mean()
print(c)

tensor(1.1639, grad_fn=<MeanBackward0>)


PyTorch has kept track of all of the operations we have done on our tensors. Now, it can go backward and calculate the gradients.

In [45]:
c.backward()

The gradient dC/dx is stored in the tensor x

In [47]:
print(x.grad)

tensor([0.7510, 0.0901, 2.6804, 0.0961, 1.8685])


*Note*: Often we calculate the gradients many times, so after every cycle we use `.grad.zero_()` to reset the gradient values.

In [48]:
x.grad.zero_()

tensor([0., 0., 0., 0., 0.])